#! /bin/sh

sxhkd &
polybar bar1 &

bspc monitor -d Web Code III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a jetbrains-idea-ce desktop='^2'
bspc rule -a Firefox desktop='^1'
bspc rule -a Pinentry state=floating
bspc rulw -a qBittorrent desktop='^0'
